import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import {useEffect} from 'react'; // 導入 useEffect
/* import Home.module.css */
import styles from '../styles/Home.module.css'


const inter = Inter({subsets: ["latin"]});

export default function Home() {
    useEffect(() => {
        // 確保在客戶端動態導入Bootstrap的JS
        typeof document !== undefined && require('bootstrap/dist/js/bootstrap.bundle.min.js');
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <nav className="navbar navbar-expand-lg navbar-light" style={{backgroundColor: "#c29ffa"}}>
                <div className="container-fluid">
                    <a className="navbar-brand" href="#">ShoppingGround</a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                            <li className="nav-item">
                                <a className="nav-link" href="#">All</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#">Clothes</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#">Electronics</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#">Furnitures</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#">Toys</a>
                            </li>
                        </ul>
                        <form className="d-flex">
                            <input className="form-control me-2" type="search" placeholder="Search"
                                   aria-label="Search"/>
                            <button className="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </>
    );
}
